source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.2.0'

# Core Rails
gem 'rails', '~> 7.1.0'

# Database
gem 'pg', '~> 1.5'

# Web server
gem 'puma', '~> 6.0'

# Authentication & OAuth
gem 'omniauth', '~> 2.1'
gem 'omniauth-oauth2', '~> 1.8'
gem 'omniauth-rails_csrf_protection', '~> 1.0'

# HTTP client
gem 'httparty', '~> 0.21'

# CORS
gem 'rack-cors', '~> 2.0'

# Rate limiting
gem 'rack-attack', '~> 6.7'

# Environment variables
gem 'dotenv-rails', '~> 2.8'

# JSON serialization
gem 'active_model_serializers', '~> 0.10'

# Background jobs (for future async processing)
gem 'sidekiq', '~> 7.0'

# Reduce boot times
gem 'bootsnap', require: false

# Timezone data
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
end

group :development do
  gem 'listen', '~> 3.8'
  gem 'spring'
end

group :test do
  gem 'shoulda-matchers', '~> 5.3'
  gem 'database_cleaner-active_record', '~> 2.1'
end
